### ISSUE TITLE
cant import repo

### ISSUE THREAD

**Issue by alxizr** [smart-fun/XmlToJson#18]
hi, i'm new to this repo. i can't pull it to my project. i get an error that the versions don't match!!

this is what i have
**implementation 'com.github.smart-fun:XmlToJson:1.4.4'**

also tried this 
**implementation 'com.github.smart-fun:XmlToJson:1.4.4-20'**

thanks

**Comment by smart-fun** [comment]
hello,
can you tell me what versions don't match ? (the exact message)

this is probably because XmlToJson uses a library (like support-annotation:27.0.2), and another library in your project also uses support-annotation with a different revision number.

What you have to do is to specify which version you want to use (the latest for example)

just add:
compile 'com.android.support:support-annotations:27.1.1'

Arnaud.
